services:
  rais:
    image: uolibraries/rais:latest
    container_name: rais
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RAIS_ADDRESS=:12415
      - RAIS_IIIFURL=http://${HOST}:8080/iiif
      - RAIS_TILEPATH=/var/local/images
      - RAIS_TILECACHELEN=10000
      - RAIS_LOGLEVEL=WARN
    volumes:
      - ${DATA_PATH}/data/Delivery:/var/local/images:ro,Z
    expose:
      - "12415"

  rais2:
    image: uolibraries/rais:latest
    container_name: rais2
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RAIS_ADDRESS=:12415
      - RAIS_IIIFURL=http://${HOST2}:8080/iiif
      - RAIS_TILEPATH=/var/local/images
      - RAIS_TILECACHELEN=10000
      - RAIS_LOGLEVEL=WARN
    volumes:
      - ${DATA_PATH}/data/Delivery:/var/local/images:ro,Z
    expose:
      - "12415"

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - rais
    # standard HTTPS
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro,Z
      - ./webroot:/srv:ro,Z
      - ./webroot2:/srv2:ro,Z
    # Caddy persistent storage (certs, configs)
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
